server:
  port: 8010

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DanielQM31/Config-Data.git
          search-paths: config-data
          username: ${GIT_USER}
          password: ${GIT_PASSWORD}

  security:
    user:
      name: user
      password: root
